apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  type: NodePort
  selector:
    app: nodeport-app
  ports:
  - port: 80         # Service Port
    targetPort: 80   # Container Port
    nodePort: 30080  # NodePort (30000-32767)
