apiVersion: v1
kind: Pod
metadata:
  name: pod-probe
  labels:
    app: probes
spec:
  containers:
  - name: myprobe-container
    image: nginx:1.29
    ports:
    - containerPort: 80

    livenessProbe:
      exec:
        command:
        - cat
        - /usr/share/nginx/html/index.html
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3

    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3

    startupProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3

               