apiVersion: v1
kind: Pod
metadata:
  name: myrestart-pod
  labels:
    app: mytest-pod
spec:
  containers:
    - name: restartcontainer
      image: jenkins/jenkins:latest
      ports:
        - containerPort: 80
  resources:
    requests:
      memory: "130Mi"
      cpu: "250m"
    limits:
        memory: "250Mi"
        cpu: "500m"
  restartPolicy: "Always"



  or




  apiVersion: v1
kind: Pod
metadata:
  name: myrestart-pod
spec:
  containers:
    - name: restartcontainer
      image: jenkins/jenkins:latest
      securityContext:
        runAsUser: 0
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1"
